Use controller-gen to generate the CRD
verrazzano/verrazzano-helidon-app-operator pull request #27
Opened 2020-12-08 11:23 UTC by bhatpmk

This PR addresses the extended validation in Kubernetes v1.18.10, which causes the error mentioned in VZ-1747 during the installation of Verrazzano.

All other details provided in https://github.com/verrazzano/verrazzano-crd-generator/pull/17, including the result of acceptance test is applicable to this PR as well

2020-12-08 13:27 UTC, markxnelson requested changes

2020-12-08 13:27 UTC, markxnelson commented on Makefile
> +	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
looks like you are introducing a new dependency here

2020-12-08 13:27 UTC, markxnelson commented on THIRD_PARTY_LICENSES.txt
>  ATTRIBUTION-HELPER-GENERATED:
this looks odd - if yhou changed go.mod, we expect to see more change than just the md5sum

2020-12-08 13:27 UTC, markxnelson commented on deploy/crds/verrazzano.io_helidonapps_crd.yaml
> +status:
status should not be here - that is an output field

2020-12-08 13:27 UTC, markxnelson commented on go.mod
> +	sigs.k8s.io/controller-tools v0.4.1 // indirect
you can `go mod tidy` to get rid of indirects before you check in, in most cases

2020-12-08 20:49 UTC, bhatpmk commented on Makefile
> +	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
@markxnelson The module controller-gen is used to generate the CRD here. This change sets the default for protocol, and there by succeeds the extended validation introduced in k8s 1.18.10. Can you please approve this new dependency ?

2020-12-08 20:51 UTC, bhatpmk commented on THIRD_PARTY_LICENSES.txt
>  ATTRIBUTION-HELPER-GENERATED:
I have run the attribution-helper and this is the only change in the THIRD_PARTY_LICENSES.txt

2020-12-08 20:51 UTC, bhatpmk commented on go.mod
> +	sigs.k8s.io/controller-tools v0.4.1 // indirect
Done

2020-12-09 12:16 UTC, bhatpmk commented
I have a clean acceptance test using OKE Cluster v1.18.10 and the test source from a branch -
https://build.verrazzano.io/job/verrazzano-magic-dns-acceptance-tests/job/pabhat%252FVZ-1747/10/

2020-12-09 13:03 UTC, mgianatagh approved these changes
I tested the changes by doing a build, generate, and ran attribution-helper.  Everything worked fine.

2020-12-09 13:21 UTC, bobdonat submitted a review, later dismissed

2020-12-11 16:40 UTC, mgianatagh approved these changes

2020-12-14 10:28 UTC, bhatpmk commented
@markxnelson I have addressed the comments you have provided to this PR. Can you please take a look at the change ?

2020-12-14 14:07 UTC, markxnelson approved these changes

2020-12-14 16:10 UTC, merged